# Generated by Django 3.1.6 on 2021-03-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('campaigns', models.CharField(blank=True, max_length=255)),
                ('influencers', models.CharField(blank=True, max_length=255)),
                ('competitors', models.CharField(blank=True, max_length=255)),
                ('safety_score', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('brand_id', models.CharField(blank=True, max_length=255)),
                ('location_id', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('age', models.CharField(blank=True, max_length=255)),
                ('kpi', models.CharField(blank=True, max_length=255)),
                ('safety_score', models.CharField(blank=True, max_length=255)),
                ('competitors', models.CharField(blank=True, max_length=255)),
                ('negotive_keyowrds', models.CharField(blank=True, max_length=255)),
                ('influencers', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('brands', models.CharField(blank=True, max_length=255)),
                ('campaigns', models.CharField(blank=True, max_length=255)),
                ('google_keyword', models.CharField(blank=True, max_length=255)),
                ('most_recent_posts', models.CharField(blank=True, max_length=255)),
                ('most_recent_images', models.CharField(blank=True, max_length=255)),
                ('highest_search_results', models.CharField(blank=True, max_length=255)),
                ('google_trends', models.CharField(blank=True, max_length=255)),
                ('following_to_follwer_ratio', models.FloatField(blank=True, default=0)),
                ('age_demo_of_audience', models.IntegerField(default=0)),
                ('location_of_audience', models.CharField(blank=True, max_length=255)),
                ('gender_demographic_of_audience', models.CharField(blank=True, max_length=255)),
                ('engagement_rate_of_audience', models.CharField(blank=True, max_length=255)),
                ('follower_change', models.CharField(blank=True, max_length=255)),
                ('accounts', models.CharField(blank=True, max_length=255)),
                ('associated_influencers', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
