# Generated by Django 3.1.6 on 2021-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210314_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
