# Generated by Django 3.1.6 on 2021-03-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_influencer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
