# Generated by Django 3.1.6 on 2021-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='influencers_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
