# Generated by Django 3.1.6 on 2021-03-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_campaign_influencers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='api_connect_stat',
            field=models.IntegerField(default=0),
        ),
    ]
