# Generated by Django 3.1.6 on 2021-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ad_keyword_negative_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='metrics',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('campaign_id', models.CharField(blank=True, max_length=255)),
                ('influencer_id', models.CharField(blank=True, max_length=255)),
                ('metrics_index', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
