# Generated by Django 3.1.6 on 2021-03-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='created_from',
            field=models.IntegerField(default=0),
        ),
    ]
