# Generated by Django 3.1.6 on 2021-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_influencer_created_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
