# Generated by Django 3.1.6 on 2021-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210324_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
