# Generated by Django 3.1.6 on 2021-03-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210326_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
