# Generated by Django 3.1.6 on 2021-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='origin_cn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='influencer',
            name='real_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
