# Generated by Django 3.1.6 on 2021-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210412_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='userid',
        ),
        migrations.AddField(
            model_name='influencer',
            name='influencer_userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='inviting_userid',
            field=models.IntegerField(default=0),
        ),
    ]
