# Generated by Django 3.1.6 on 2021-04-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210412_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='inviting_userid',
            new_name='userid',
        ),
    ]
