# Generated by Django 3.1.6 on 2021-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_campaign_influencers_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='influencers_campaign_writeup',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
