# Generated by Django 3.1.6 on 2021-05-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_campaign_influencers_campaign_writeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram_user_audience_country',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ig_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('influencer_id', models.CharField(blank=True, max_length=255)),
                ('lifetime_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('values', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='instagram_user_audience_gender_age',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('influencer_id', models.CharField(blank=True, max_length=255)),
                ('ig_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('lifetime_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('values', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='instagram_user_comments',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('influencer_id', models.CharField(blank=True, max_length=255)),
                ('ig_id', models.CharField(blank=True, max_length=255)),
                ('post_id', models.CharField(blank=True, max_length=255)),
                ('comment_id', models.CharField(blank=True, max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='instagram_user_medias',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('influencer_id', models.CharField(blank=True, max_length=255)),
                ('ig_id', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('ig_zid', models.CharField(blank=True, max_length=255)),
                ('comments_count', models.CharField(blank=True, max_length=255)),
                ('like_count', models.CharField(blank=True, max_length=255)),
                ('media_url', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=255)),
                ('permalink', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.CharField(blank=True, max_length=255)),
                ('impression', models.CharField(blank=True, max_length=255)),
                ('reach', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='instagram_user_profile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('influencer_id', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, unique=True)),
                ('ig_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('biography', models.CharField(blank=True, max_length=255)),
                ('ig_num_id', models.CharField(blank=True, max_length=255)),
                ('followers_count', models.CharField(blank=True, max_length=255)),
                ('follows_count', models.CharField(blank=True, max_length=255)),
                ('media_count', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
