# Generated by Django 3.1.6 on 2021-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_instagram_user_medias_ig_zid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='comments_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='impression',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='reach',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram_user_profile',
            name='followers_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram_user_profile',
            name='follows_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram_user_profile',
            name='media_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
