# Generated by Django 3.1.6 on 2021-05-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210504_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_user_audience_country',
            name='values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagram_user_audience_gender_age',
            name='values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagram_user_comments',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagram_user_profile',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
