# Generated by Django 3.1.6 on 2021-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210504_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='media_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagram_user_medias',
            name='permalink',
            field=models.TextField(blank=True),
        ),
    ]
