"""
Django settings for eaeo project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


from decouple import config, Csv
import dj_database_url
from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3n#bqa7ipjgk6xgh@a03%6re+*!ir^d77*ea0i9(7xm9c2yk=c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps

    'social_django',
    "sslserver",
    "bootstrap5",
    # Project apps
    "main",
    "html2pdf",
    "task"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #heroku
    'middleware.PathHandling.PathHandlingMiddleware'
]

ROOT_URLCONF = 'eaeo.urls'

AUTH_USER_MODEL = 'main.tbl_user'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'eaeo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
PRODUCTIONDB = 1

if PRODUCTIONDB:
    DATABASES = {
        'default': {
            'HOST': 'db-mysql-lon1-69602-do-user-8709659-0.b.db.ondigitalocean.com',
            'PORT': '25060',
            'NAME': 'defaultdb',
            'ENGINE': 'django.db.backends.mysql',
            'USER': 'doadmin',
            'PASSWORD': 'nki8r9sgz2cdnwve',
            'ATOMIC_REQUESTS': True,
        },
    }
else:
    DATABASES = {
        'default': {
            'HOST': 'localhost',
            'NAME': 'eaeo_db',
            'ENGINE': 'django.db.backends.mysql',
            'USER': 'root',
            'PASSWORD': '',
            'ATOMIC_REQUESTS': True
        },
    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #heroku
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' #heroku

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend'
)

# SOCIAL_AUTH_USER_MODEL = 'main.tbl_user'
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_FACEBOOK_KEY = '433294417989709'
SOCIAL_AUTH_FACEBOOK_SECRET = 'a541eb397904b41763aa631c99078f81'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['instagram_basic', 'pages_show_list', 'pages_read_engagement', 'instagram_manage_insights']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,picture,accounts.fields(id,name,picture,tasks,category,instagram_business_account.fields(id,name,username,profile_picture_url))'
}
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = ['id', 'name', 'picture', 'accounts']
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/new_social_auth_user'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/social_error_url'

SOCIAL_AUTH_ACCESS_TOKEN = 'EAAGKFDfeEE0BAEjOu8xMijlObVx4ZBbXKRgpYLT4IvaPnGOadvu55OsG5oy0t8srV3224ytP6wM7xK4CFxBKRj7TwmQGQu55KnaUwjLLvntERz02ZBvkutjjWF1DPkyJ0iEVH73aIoS9ZCXjsT96IWlkCRZBtCUaNztHcJykWAZDZD'
SOCIAL_AUTH_INSTAGRAM_ADMIN_BUSINESSID = '17841407968025388'

LOGIN_URL = '/'


